name: Publish to GitHub Packages

on:
  release:
    types: [ published ]

jobs:
  build-and-publish-github-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'liberica'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # v4.0.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish to Github Packages
        run: ./gradlew test -DGITHUB_USERNAME=${{ github.actor }} -DGITHUB_TOKEN=${{ github.token }} publish
